export default {
  name: "namrkwejrk",
  password: "sdkflajsdsdf",
  requestConfig: {
    method: "post",
    maxBodyLength: Infinity,
    headers: {
      "sec-ch-ua":
        '"Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"',
      "Next-Router-State-Tree":
        "%5B%22%22%2C%7B%22children%22%3A%5B%22admin%22%2C%7B%22children%22%3A%5B%22__PAGE__%22%2C%7B%7D%5D%7D%5D%7D%2Cnull%2Cnull%2Ctrue%5D",
      "sec-ch-ua-mobile": "?0",
      "User-Agent":
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
      Accept: "text/x-component",
      "Next-Action": "a221b071140e55563e91a3226c508cb229c121f6",
      "sec-ch-ua-platform": '"macOS"',
      "Content-Type": "application/json",
    },
  },
  emailAddresses: [
    "rupolia8@mail.com",
    "coderankitkumar@gmail.com",
    "poojakesharwani2020@gmail.com",
    "naman.naresh.14@gmail.com",
    "vjchouhan5@gmail.com",
    "pawansah0906@gmail.com",
    "bhupendrapa1730@gmail.com",
    "rajakjaya94@gmail.com",
    "abhaydongre15@gmail.com",
    "as318444@gmail.com",
    "okteprateek@gmail.com",
    "abhishekopm404@gmail.com",
    "mksavita8@gmail.com",
    "rt13853@gmail.com",
    "sunandanmishra24@gmail.com",
    "shrivastavad34@gmail.com",
    "diwakar.92505@gmail.com",
    "mpalohiya@gmail.com",
    "ashishsingh3408@gmail.com",
    "vinitsammir2@gmail.com",
    "dkalawat23@gmail.com",
    "sanidhyanigam99@gmail.com",
    "rudrapandey170@gmail.com",
    "ns32545@gmail.com",
    "dpkkmrdubey@yahoo.com",
    "akshatakshat.agrawal0@gmail.com",
    "bhartisharma1122333@gmail.com",
    "champnaaz@gmail.com",
    "amishavish60@gmail.com",
    "saketanand256@gmail.com",
    "naman.tiwari208@gmail.com",
    "arman.khan152@gmail.com",
    "animeshn153@gmail.com",
    "mintumishra249@gmail.com",
    "dwivediprateek380@gmail.com",
    "dwivediprateek52@gmail.com",
    "ksudarshan944@gmail.com",
    "bhumikasingour68382@gmail.com",
    "pythoncoder85@gmail.com",
    "sangamkhare05@gmail.com",
    "siddiqueshoaib18@gmail.com",
    "tripathiravi850@gmail.com",
    "sharmapandey042@gmail.com",
    "indrajeetkumarmth11@gmail.com",
    "ashudeepankar184@gmail.com",
    "chirayupawar123456@gmail.com",
  ],
};
